services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  backend:
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
       /app/node_modules
    ports:
      - "5001:${PORT:-5001}"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "${MONGODB_URI:-mongodb://mongo:27017/nwave}"

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: