services:
  backend:
    image: hcistudio/nwave-backend:latest
    env_file: .env.backend
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/nwave"

  frontend:
    image: hcistudio/nwave-frontend:latest
    ports:
      - "5173:5173"

  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: