// Builds a self-contained Nextflow project from a generated workflow script:
// the files the backend would otherwise add at run time (module config,
// nf-core module files, input files) plus a README with the run command.

/** Pinned Nextflow version the generated scripts are tested with. */
export const DEFAULT_NEXTFLOW_VERSION = "25.04.4";

export interface ProjectInputFile {
  name: string;
  /** File content; undefined when the workflow only knows the file name. */
  content?: string;
}

export interface ProjectExportInput {
  workflowName: string;
  /** The generated (or imported) Nextflow script. */
  script: string;
  inputFiles: ProjectInputFile[];
  /** nf-core module files keyed by module path ("fastqc", "star/align"). */
  moduleFiles: Record<string, Record<string, string>>;
  nextflowVersion?: string;
}

/**
 * Split the config the generator embeds in `N-WAVE_NEXTFLOW_CONFIG`
 * comments out of the script. Mirrors extractNwaveNextflowAssets in
 * backend/src/execution/nextflowScript.ts.
 */
export const extractNextflowConfig = (
  script: string,
): { script: string; config: string } => {
  const configBlocks: string[] = [];
  const cleaned = script.replace(
    /\/\*\s*N-WAVE_NEXTFLOW_CONFIG\s*([\s\S]*?)\*\//g,
    (_match, block: string) => {
      configBlocks.push(block.trim());
      return "";
    },
  );
  return {
    script: cleaned.replace(/\n{3,}/g, "\n\n"),
    config: configBlocks.filter(Boolean).join("\n\n"),
  };
};

/**
 * nf-core modules a script includes, by module path ("star/align").
 * Mirrors getReferencedNfCoreModules in the backend.
 */
export const getReferencedNfCoreModules = (script: string): string[] => {
  const modules = new Set<string>();
  for (const match of script.matchAll(
    /from\s+['"]\.\/modules\/nf-core\/([A-Za-z0-9_/-]+)\/main['"]/g,
  )) {
    const modulePath = match[1];
    if (
      modulePath &&
      !modulePath.split("/").some((segment) => !segment || segment === "..")
    ) {
      modules.add(modulePath);
    }
  }
  return Array.from(modules).sort();
};

/** A folder/file-name friendly version of the workflow name. */
export const toProjectName = (workflowName: string): string =>
  workflowName
    .trim()
    .replace(/[^A-Za-z0-9._-]+/g, "_")
    .replace(/^[._]+|_+$/g, "") || "workflow";

const isPlainFileName = (name: string): boolean =>
  /^[^/\\]+$/.test(name) && name !== "." && name !== "..";

/** A relative path without "..": "main.nf", "templates/tximport.r". */
const isSafeRelativePath = (filePath: string): boolean =>
  filePath.split("/").every(isPlainFileName);

export const buildNextflowConfig = (generatedConfig: string): string =>
  [
    "// Generated by N-WAVE.",
    "// Run with: nextflow run main.nf -profile docker",
    "",
    "params {",
    "  outdir   = 'results'",
    '  inputdir = "${projectDir}/inputs"',
    "}",
    ...(generatedConfig.trim()
      ? ["", "// Module settings from the N-WAVE nodes", generatedConfig.trim()]
      : []),
    "",
    "profiles {",
    "  docker {",
    "    docker.enabled = true",
    "    // Run as the calling user, so outputs aren't owned by root and",
    "    // images with a non-root default user can write to the task dir.",
    "    docker.runOptions = '-u $(id -u):$(id -g)'",
    "  }",
    "}",
    "",
  ].join("\n");

export const buildReadme = ({
  projectName,
  workflowName,
  modules,
  inputFiles,
  nextflowVersion,
}: {
  projectName: string;
  workflowName: string;
  modules: string[];
  inputFiles: ProjectInputFile[];
  nextflowVersion: string;
}): string => {
  const included = inputFiles.filter((file) => file.content !== undefined);
  const missing = inputFiles.filter((file) => file.content === undefined);

  return [
    `# ${workflowName}`,
    "",
    "A Nextflow workflow exported from [N-WAVE](https://github.com/HCIstudio/N-WAVE).",
    "",
    "## Requirements",
    "",
    `- [Nextflow](https://www.nextflow.io/docs/latest/install.html) (tested with ${nextflowVersion})`,
    "- [Docker](https://docs.docker.com/get-docker/), running",
    "",
    "## Run",
    "",
    "```bash",
    `cd ${projectName}`,
    "nextflow run main.nf -profile docker",
    "```",
    "",
    "Outputs of Display Output nodes are written to `results/`; intermediate files",
    "stay in Nextflow's `work/` directory. Use `--outdir <dir>` to write results",
    "elsewhere and `-resume` to continue a run.",
    "",
    "## Inputs",
    "",
    ...(inputFiles.length === 0
      ? ["This workflow reads no input files."]
      : [
          "Input files are read from `inputs/` (change with `--inputdir <dir>`).",
          "",
          ...included.map((file) => `- \`inputs/${file.name}\` (included)`),
          ...missing.map(
            (file) =>
              `- \`inputs/${file.name}\`: **not included**, add this file before running`,
          ),
        ]),
    "",
    "## Contents",
    "",
    "- `main.nf`: the workflow",
    "- `nextflow.config`: parameters, module settings and the `docker` profile",
    ...(modules.length > 0
      ? [
          "- `modules/nf-core/`: the nf-core modules the workflow uses:",
          ...modules.map((module) => `  - \`${module}\``),
        ]
      : []),
    ...(inputFiles.length > 0 ? ["- `inputs/`: input files"] : []),
    "",
  ].join("\n");
};

/**
 * All files of the exported project, keyed by path inside the project
 * folder. Throws when a module the script includes has no files.
 */
export const buildProjectFiles = (
  input: ProjectExportInput,
): Record<string, string> => {
  const projectName = toProjectName(input.workflowName);
  const { script, config } = extractNextflowConfig(input.script);
  const modules = getReferencedNfCoreModules(script);
  const nextflowVersion = input.nextflowVersion || DEFAULT_NEXTFLOW_VERSION;

  const files: Record<string, string> = {
    "main.nf": script,
    "nextflow.config": buildNextflowConfig(config),
    "README.md": buildReadme({
      projectName,
      workflowName: input.workflowName || projectName,
      modules,
      inputFiles: input.inputFiles,
      nextflowVersion,
    }),
  };

  for (const module of modules) {
    const moduleFiles = input.moduleFiles[module];
    if (!moduleFiles?.["main.nf"]) {
      throw new Error(`Missing files for nf-core module ${module}.`);
    }
    for (const [name, content] of Object.entries(moduleFiles)) {
      if (isSafeRelativePath(name)) {
        files[`modules/nf-core/${module}/${name}`] = content;
      }
    }
  }

  for (const file of input.inputFiles) {
    if (file.content !== undefined && isPlainFileName(file.name)) {
      files[`inputs/${file.name}`] = file.content;
    }
  }

  return files;
};

/**
 * Zip the project into a single folder named after the workflow. fflate is
 * loaded on demand so it stays out of the main bundle.
 */
export const zipProject = async (
  workflowName: string,
  files: Record<string, string>,
): Promise<Blob> => {
  const { strToU8, zipSync } = await import("fflate");
  const projectName = toProjectName(workflowName);
  const entries = Object.fromEntries(
    Object.entries(files).map(([filePath, content]) => [
      `${projectName}/${filePath}`,
      strToU8(content),
    ]),
  );
  const zipped = zipSync(entries, { level: 6 });
  return new Blob([zipped], { type: "application/zip" });
};
