// Builds a self-contained Nextflow project from a generated workflow script:
// the files the backend would otherwise add at run time (module config,
// nf-core module and subworkflow files, input files) plus a README with the
// run command.

import { getSubworkflowIncludes } from "../registry/nfcore/subworkflowSource";
import {
  type PipelineLaunch,
  pipelineParamsFile,
} from "../registry/pipelines/launch";

/** Pinned Nextflow version the generated scripts are tested with. */
export const DEFAULT_NEXTFLOW_VERSION = "25.04.4";

export interface ProjectInputFile {
  name: string;
  /** File content; undefined when the workflow only knows the file name. */
  content?: string;
}

export interface ProjectExportInput {
  workflowName: string;
  /** The generated (or imported) Nextflow script. */
  script: string;
  inputFiles: ProjectInputFile[];
  /** nf-core module files keyed by module path ("fastqc", "star/align"). */
  moduleFiles: Record<string, Record<string, string>>;
  /** nf-core subworkflow files keyed by name ("bam_stats_samtools"). */
  subworkflowFiles?: Record<string, Record<string, string>>;
  nextflowVersion?: string;
}

/**
 * Split the config the generator embeds in `N-WAVE_NEXTFLOW_CONFIG`
 * comments out of the script. Mirrors extractNwaveNextflowAssets in
 * backend/src/execution/nextflowScript.ts.
 */
export const extractNextflowConfig = (
  script: string,
): { script: string; config: string } => {
  const configBlocks: string[] = [];
  const cleaned = script.replace(
    /\/\*\s*N-WAVE_NEXTFLOW_CONFIG\s*([\s\S]*?)\*\//g,
    (_match, block: string) => {
      configBlocks.push(block.trim());
      return "";
    },
  );
  return {
    script: cleaned.replace(/\n{3,}/g, "\n\n"),
    config: configBlocks.filter(Boolean).join("\n\n"),
  };
};

/**
 * nf-core modules a script includes, by module path ("star/align").
 * Mirrors getReferencedNfCoreModules in the backend.
 */
export const getReferencedNfCoreModules = (script: string): string[] => {
  const modules = new Set<string>();
  for (const match of script.matchAll(
    /from\s+['"]\.\/modules\/nf-core\/([A-Za-z0-9_/-]+)\/main['"]/g,
  )) {
    const modulePath = match[1];
    if (
      modulePath &&
      !modulePath.split("/").some((segment) => !segment || segment === "..")
    ) {
      modules.add(modulePath);
    }
  }
  return Array.from(modules).sort();
};

/**
 * nf-core subworkflows a script includes, by name ("bam_stats_samtools").
 * Mirrors getReferencedNfCoreSubworkflows in the backend.
 */
export const getReferencedNfCoreSubworkflows = (script: string): string[] => {
  const subworkflows = new Set<string>();
  for (const match of script.matchAll(
    /from\s+['"]\.\/subworkflows\/nf-core\/([A-Za-z0-9_-]+)\/main['"]/g,
  )) {
    subworkflows.add(match[1]);
  }
  return Array.from(subworkflows).sort();
};

/**
 * Every nf-core module and subworkflow a project needs: the ones the script
 * includes plus, recursively, the ones those subworkflows include.
 * `subworkflowSource` returns a subworkflow's main.nf (or undefined when it
 * isn't known yet).
 */
export const resolveNfCoreComponents = (
  script: string,
  subworkflowSource: (name: string) => string | undefined,
): { modules: string[]; subworkflows: string[]; unresolved: string[] } => {
  const modules = new Set(getReferencedNfCoreModules(script));
  const subworkflows = new Set<string>();
  const unresolved: string[] = [];
  const queue = getReferencedNfCoreSubworkflows(script);
  while (queue.length > 0) {
    const name = queue.shift() as string;
    if (subworkflows.has(name)) continue;
    subworkflows.add(name);
    const source = subworkflowSource(name);
    if (source === undefined) {
      unresolved.push(name);
      continue;
    }
    const includes = getSubworkflowIncludes(source);
    for (const module of includes.modules) modules.add(module);
    queue.push(...includes.subworkflows);
  }
  return {
    modules: Array.from(modules).sort(),
    subworkflows: Array.from(subworkflows).sort(),
    unresolved,
  };
};

/** A folder/file-name friendly version of the workflow name. */
export const toProjectName = (workflowName: string): string =>
  workflowName
    .trim()
    .replace(/[^A-Za-z0-9._-]+/g, "_")
    .replace(/^[._]+|_+$/g, "") || "workflow";

const isPlainFileName = (name: string): boolean =>
  /^[^/\\]+$/.test(name) && name !== "." && name !== "..";

/** A relative path without "..": "main.nf", "templates/tximport.r". */
const isSafeRelativePath = (filePath: string): boolean =>
  filePath.split("/").every(isPlainFileName);

export const buildNextflowConfig = (generatedConfig: string): string =>
  [
    "// Generated by N-WAVE.",
    "// Run with: nextflow run main.nf -profile docker",
    "",
    "params {",
    "  outdir   = 'results'",
    '  inputdir = "${projectDir}/inputs"',
    "}",
    ...(generatedConfig.trim()
      ? ["", "// Module settings from the N-WAVE nodes", generatedConfig.trim()]
      : []),
    "",
    "profiles {",
    "  docker {",
    "    docker.enabled = true",
    "    // Run as the calling user, so outputs aren't owned by root and",
    "    // images with a non-root default user can write to the task dir.",
    "    docker.runOptions = '-u $(id -u):$(id -g)'",
    "  }",
    "}",
    "",
  ].join("\n");

export const buildReadme = ({
  projectName,
  workflowName,
  modules,
  subworkflows = [],
  inputFiles,
  nextflowVersion,
}: {
  projectName: string;
  workflowName: string;
  modules: string[];
  subworkflows?: string[];
  inputFiles: ProjectInputFile[];
  nextflowVersion: string;
}): string => {
  const included = inputFiles.filter((file) => file.content !== undefined);
  const missing = inputFiles.filter((file) => file.content === undefined);

  return [
    `# ${workflowName}`,
    "",
    "A Nextflow workflow exported from [N-WAVE](https://github.com/HCIstudio/N-WAVE).",
    "",
    "## Requirements",
    "",
    `- [Nextflow](https://www.nextflow.io/docs/latest/install.html) (tested with ${nextflowVersion})`,
    "- [Docker](https://docs.docker.com/get-docker/), running",
    "",
    "## Run",
    "",
    "```bash",
    `cd ${projectName}`,
    "nextflow run main.nf -profile docker",
    "```",
    "",
    "Outputs of Display Output nodes are written to `results/`; intermediate files",
    "stay in Nextflow's `work/` directory. Use `--outdir <dir>` to write results",
    "elsewhere and `-resume` to continue a run.",
    "",
    "## Inputs",
    "",
    ...(inputFiles.length === 0
      ? ["This workflow reads no input files."]
      : [
          "Input files are read from `inputs/` (change with `--inputdir <dir>`).",
          "",
          ...included.map((file) => `- \`inputs/${file.name}\` (included)`),
          ...missing.map(
            (file) =>
              `- \`inputs/${file.name}\`: **not included**, add this file before running`,
          ),
        ]),
    "",
    "## Contents",
    "",
    "- `main.nf`: the workflow",
    "- `nextflow.config`: parameters, module settings and the `docker` profile",
    ...(modules.length > 0
      ? [
          "- `modules/nf-core/`: the nf-core modules the workflow uses:",
          ...modules.map((module) => `  - \`${module}\``),
        ]
      : []),
    ...(subworkflows.length > 0
      ? [
          "- `subworkflows/nf-core/`: the nf-core subworkflows the workflow uses:",
          ...subworkflows.map((subworkflow) => `  - \`${subworkflow}\``),
        ]
      : []),
    ...(inputFiles.length > 0 ? ["- `inputs/`: input files"] : []),
    "",
  ].join("\n");
};

/**
 * All files of the exported project, keyed by path inside the project
 * folder. Throws when a module the script includes has no files.
 */
export const buildProjectFiles = (
  input: ProjectExportInput,
): Record<string, string> => {
  const projectName = toProjectName(input.workflowName);
  const { script, config } = extractNextflowConfig(input.script);
  const subworkflowFiles = input.subworkflowFiles ?? {};
  const { modules, subworkflows, unresolved } = resolveNfCoreComponents(
    script,
    (name) => subworkflowFiles[name]?.["main.nf"],
  );
  if (unresolved.length > 0) {
    throw new Error(`Missing files for nf-core subworkflow ${unresolved[0]}.`);
  }
  const nextflowVersion = input.nextflowVersion || DEFAULT_NEXTFLOW_VERSION;

  const files: Record<string, string> = {
    "main.nf": script,
    "nextflow.config": buildNextflowConfig(config),
    "README.md": buildReadme({
      projectName,
      workflowName: input.workflowName || projectName,
      modules,
      subworkflows,
      inputFiles: input.inputFiles,
      nextflowVersion,
    }),
  };

  for (const subworkflow of subworkflows) {
    for (const [name, content] of Object.entries(
      subworkflowFiles[subworkflow] ?? {},
    )) {
      if (isSafeRelativePath(name)) {
        files[`subworkflows/nf-core/${subworkflow}/${name}`] = content;
      }
    }
  }

  for (const module of modules) {
    const moduleFiles = input.moduleFiles[module];
    if (!moduleFiles?.["main.nf"]) {
      throw new Error(`Missing files for nf-core module ${module}.`);
    }
    for (const [name, content] of Object.entries(moduleFiles)) {
      if (isSafeRelativePath(name)) {
        files[`modules/nf-core/${module}/${name}`] = content;
      }
    }
  }

  for (const file of input.inputFiles) {
    if (file.content !== undefined && isPlainFileName(file.name)) {
      files[`inputs/${file.name}`] = file.content;
    }
  }

  return files;
};

/**
 * The project for a workflow with a Pipeline node: the launch command (in
 * README.md and run.sh), the params file and the input files. The pipeline
 * itself is pulled from GitHub by Nextflow.
 */
export const buildPipelineProjectFiles = ({
  workflowName,
  launch,
  nextflowVersion = DEFAULT_NEXTFLOW_VERSION,
}: {
  workflowName: string;
  launch: PipelineLaunch;
  nextflowVersion?: string;
}): Record<string, string> => {
  const projectName = toProjectName(workflowName);
  const included = launch.inputFiles.filter((file) => file.content !== undefined);
  const missing = launch.inputFiles.filter((file) => file.content === undefined);
  const files: Record<string, string> = {
    "run.sh": `#!/usr/bin/env bash\n# Generated by N-WAVE.\nset -euo pipefail\ncd "$(dirname "$0")"\n${launch.command} "$@"\n`,
    "README.md": [
      `# ${workflowName || projectName}`,
      "",
      `Runs [nf-core/${launch.name}](https://nf-co.re/${launch.name}/${launch.version}) ${launch.version}, exported from [N-WAVE](https://github.com/HCIstudio/N-WAVE).`,
      "",
      "## Requirements",
      "",
      `- [Nextflow](https://www.nextflow.io/docs/latest/install.html) (tested with ${nextflowVersion})`,
      "- [Docker](https://docs.docker.com/get-docker/), running",
      "",
      "## Run",
      "",
      "```bash",
      `cd ${projectName}`,
      launch.command,
      "```",
      "",
      "or `./run.sh`. Nextflow downloads the pipeline and its containers on the first run.",
      "Results are written to `results/` (the MultiQC report is under `results/multiqc/`).",
      "Add `-resume` to continue a run.",
      "",
      ...(Object.keys(launch.params).length > 0
        ? ["Parameters are in `params.json`.", ""]
        : []),
      ...(launch.inputFiles.length > 0
        ? [
            "## Inputs",
            "",
            ...included.map((file) => `- \`inputs/${file.name}\` (included)`),
            ...missing.map(
              (file) =>
                `- \`inputs/${file.name}\`: **not included**, add this file before running`,
            ),
            "",
          ]
        : []),
    ].join("\n"),
  };
  if (Object.keys(launch.params).length > 0) {
    files["params.json"] = pipelineParamsFile(launch);
  }
  for (const file of included) {
    if (isPlainFileName(file.name)) {
      files[`inputs/${file.name}`] = file.content as string;
    }
  }
  return files;
};

/**
 * Zip the project into a single folder named after the workflow. fflate is
 * loaded on demand so it stays out of the main bundle.
 */
export const zipProject = async (
  workflowName: string,
  files: Record<string, string>,
): Promise<Blob> => {
  const { strToU8, zipSync } = await import("fflate");
  const projectName = toProjectName(workflowName);
  const entries = Object.fromEntries(
    Object.entries(files).map(([filePath, content]) => [
      `${projectName}/${filePath}`,
      strToU8(content),
    ]),
  );
  const zipped = zipSync(entries, { level: 6 });
  return new Blob([zipped], { type: "application/zip" });
};
