import os from "node:os";

// CPU, memory and time limits for workflow runs. The host (or the admin, via
// NWAVE_MAX_CPUS / NWAVE_MAX_MEMORY) sets a ceiling; each run asks for its
// own limits in the execution settings and gets them clamped to the
// ceiling. Nextflow applies the result to every process through
// `process.resourceLimits`, so a module that asks for more is capped
// instead of failing.

const KB = 1024;
const MB = 1024 ** 2;
const GB = 1024 ** 3;
const UNITS: Record<string, number> = { B: 1, KB, MB, GB, TB: 1024 ** 4 };

/** Bytes in a memory amount such as "8 GB", "8.GB", "512MB" or "8G"; null if invalid. */
export const parseMemory = (value: string | undefined): number | null => {
  const match = value
    ?.trim()
    .match(/^(\d+(?:\.\d+)?)\s*\.?\s*([KMGT]?)B?$/i);
  if (!match) return null;
  const amount = Number(match[1]);
  const unit = `${(match[2] ?? "").toUpperCase()}B`;
  const bytes = amount * (UNITS[unit] ?? 1);
  return Number.isFinite(bytes) && bytes > 0 ? Math.floor(bytes) : null;
};

/** A memory amount in Nextflow's notation, rounded down: "12.GB", "512.MB". */
export const formatMemory = (bytes: number): string => {
  if (bytes >= GB) return `${Math.max(1, Math.floor(bytes / GB))}.GB`;
  if (bytes >= MB) return `${Math.floor(bytes / MB)}.MB`;
  return `${Math.max(1, Math.floor(bytes / KB))}.KB`;
};

export interface HostResources {
  cpus: number;
  /** Bytes. */
  memory: number;
}

/** CPUs and memory of this machine (or of the backend's cgroup, if smaller). */
export const detectHostResources = (): HostResources => {
  const total = os.totalmem();
  const constrained =
    typeof process.constrainedMemory === "function" ? process.constrainedMemory() : 0;
  return {
    cpus:
      typeof os.availableParallelism === "function"
        ? os.availableParallelism()
        : os.cpus().length,
    memory: constrained > 0 && constrained < total ? constrained : total,
  };
};

/** Share of the host's memory runs may use unless NWAVE_MAX_MEMORY says otherwise. */
export const DEFAULT_MEMORY_SHARE = 0.8;

export interface ResourceCeiling {
  cpus: number;
  /** Bytes. */
  memory: number;
  /** Where each value came from, for messages. */
  source: { cpus: "env" | "host"; memory: "env" | "host" };
}

/**
 * The most any run may use: NWAVE_MAX_CPUS and NWAVE_MAX_MEMORY when set
 * (and valid), otherwise all host CPUs and 80% of host memory.
 */
export const resolveResourceCeiling = (
  env: NodeJS.ProcessEnv = process.env,
  host: HostResources = detectHostResources(),
): ResourceCeiling => {
  const envCpus = Number.parseInt(env.NWAVE_MAX_CPUS ?? "", 10);
  const envMemory = parseMemory(env.NWAVE_MAX_MEMORY);
  return {
    cpus: envCpus > 0 ? envCpus : Math.max(1, host.cpus),
    memory: envMemory ?? Math.max(GB, Math.floor(host.memory * DEFAULT_MEMORY_SHARE)),
    source: {
      cpus: envCpus > 0 ? "env" : "host",
      memory: envMemory ? "env" : "host",
    },
  };
};

export interface RunResourceLimits {
  cpus: number;
  /** Nextflow notation, e.g. "12.GB". */
  memory: string;
  /** Which requested values were lowered to the ceiling. */
  capped: { cpus: boolean; memory: boolean };
  ceiling: ResourceCeiling;
}

/**
 * Limits for one run: the requested CPUs and memory (defaults: 4 CPUs,
 * 4 GB), clamped to the ceiling.
 */
export const resolveRunLimits = (
  requested: { maxCpus?: number; maxMemory?: string },
  ceiling: ResourceCeiling = resolveResourceCeiling(),
): RunResourceLimits => {
  const wantedCpus = Math.max(1, Math.floor(Number(requested.maxCpus) || 4));
  const wantedMemory = parseMemory(requested.maxMemory) ?? 4 * GB;
  return {
    cpus: Math.min(wantedCpus, ceiling.cpus),
    memory: formatMemory(Math.min(wantedMemory, ceiling.memory)),
    capped: {
      cpus: wantedCpus > ceiling.cpus,
      memory: wantedMemory > ceiling.memory,
    },
    ceiling,
  };
};

/** `process.resourceLimits` for a run's Nextflow config. */
export const buildResourceLimitsConfig = (limits: { cpus: number; memory: string }): string =>
  [
    "// Generated by N-WAVE: resource limits for this run. Processes that ask",
    "// for more are capped to these.",
    "process {",
    `  resourceLimits = [ cpus: ${limits.cpus}, memory: '${limits.memory}' ]`,
    "}",
  ].join("\n");

/** Default run time limit in minutes when a run doesn't set one (24 hours). */
export const DEFAULT_TIMEOUT_MINUTES = 24 * 60;

/**
 * Run time limit in milliseconds, or 0 for none: the run's own limit when
 * set, otherwise NWAVE_EXECUTION_TIMEOUT (minutes; 0 = no limit), otherwise
 * 24 hours.
 */
export const resolveTimeoutMs = (
  runMinutes: number | undefined,
  env: NodeJS.ProcessEnv = process.env,
): number => {
  if (runMinutes && runMinutes > 0) return Math.round(runMinutes * 60_000);
  const configured = env.NWAVE_EXECUTION_TIMEOUT?.trim();
  if (configured !== undefined && configured !== "" && /^\d+(\.\d+)?$/.test(configured)) {
    return Math.round(Number(configured) * 60_000);
  }
  return DEFAULT_TIMEOUT_MINUTES * 60_000;
};

/** Human-readable size, e.g. "12.0 GB". */
export const describeMemory = (bytes: number): string =>
  `${(bytes / GB).toFixed(1)} GB`;

/** One line describing a run's limits, for the run's output. */
export const describeRunLimits = (limits: RunResourceLimits, timeoutMs: number): string => {
  const parts = [
    `${limits.cpus} CPU${limits.cpus === 1 ? "" : "s"}`,
    `${limits.memory.replace(".", " ")} memory`,
    timeoutMs > 0 ? `time limit ${Math.round(timeoutMs / 60_000)} min` : "no time limit",
  ];
  const capped = [
    limits.capped.cpus ? `CPUs to ${limits.ceiling.cpus}` : "",
    limits.capped.memory ? `memory to ${describeMemory(limits.ceiling.memory)}` : "",
  ].filter(Boolean);
  return `N-WAVE limits: ${parts.join(", ")}${
    capped.length > 0
      ? ` (lowered ${capped.join(" and ")}, the most this server allows; see NWAVE_MAX_CPUS / NWAVE_MAX_MEMORY)`
      : ""
  }`;
};

/**
 * Why a failed run's output suggests it ran out of resources, as a message
 * for the user, or null when nothing points that way.
 */
export const diagnoseResourceFailure = (
  output: string,
  limits?: { cpus: number; memory: string },
): string | null => {
  const raise = limits
    ? ` Raise Maximum CPU Cores / Maximum Memory in the execution settings (this run had ${limits.cpus} CPUs and ${limits.memory.replace(".", " ")}), or NWAVE_MAX_CPUS / NWAVE_MAX_MEMORY on the server.`
    : " Raise the limits in the execution settings, or NWAVE_MAX_CPUS / NWAVE_MAX_MEMORY on the server.";
  const memoryRequirement = output.match(
    /Process requirement exceeds available memory -- req: ([^;\n]+); avail: ([^\n]+)/,
  );
  if (memoryRequirement) {
    return `A task needed ${memoryRequirement[1]?.trim()} of memory, but only ${memoryRequirement[2]?.trim()} was available.${raise}`;
  }
  const cpuRequirement = output.match(
    /Process requirement exceeds available CPUs -- req: ([^;\n]+); avail: ([^\n]+)/,
  );
  if (cpuRequirement) {
    return `A task needed ${cpuRequirement[1]?.trim()} CPUs, but only ${cpuRequirement[2]?.trim()} were available.${raise}`;
  }
  if (
    /Command exit status:\s*\n?\s*137\b/.test(output) ||
    /\bexit status (?:of )?\(?137\b/i.test(output) ||
    /java\.lang\.OutOfMemoryError|std::bad_alloc|\bOut of memory\b|\bOOMKilled\b/i.test(output)
  ) {
    return `A task ran out of memory (it was killed, exit status 137, or reported an out-of-memory error).${raise}`;
  }
  return null;
};
