name: Build and push Docker images
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: [ubuntu-22.04]
    strategy:
      matrix:
         component:
          - name: backend
            context: ./backend
            dockerfile: ./backend/Dockerfile
            image: hcistudio/nwave-backend
          - name: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile
            image: hcistudio/nwave-frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push ${{ matrix.component.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.dockerfile }}
          push: true
          tags: |
            ${{ matrix.component.image }}:latest
            ${{ matrix.component.image }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ matrix.component.image }}:buildcache
          cache-to: type=registry,ref=${{ matrix.component.image }}:buildcache,mode=max



