name: CI

on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
  build-images-check:
    name: Build images (no push)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          platforms: linux/amd64     
          push: false                
          load: true                 
          provenance: false          
          sbom: false

      - name: Build frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          provenance: false
          sbom: false
