name: Release assets
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'test'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            deploy/docker-compose.yml
            deploy/.env.example
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}